# -*- coding: utf-8 -*-

"""
whatsappcloudapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MarkMessageAsReadRequest(object):

    """Implementation of the 'MarkMessageAsReadRequest' model.

    TODO: type model description here.

    Attributes:
        messaging_product (string): Messaging service used for the request.
            Use 'whatsapp'.
        status (string): A message's status. You can use this field to mark a
            message as read.
        message_id (string): Id of the incoming message.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "messaging_product": 'messaging_product',
        "status": 'status',
        "message_id": 'message_id'
    }

    def __init__(self,
                 messaging_product=None,
                 status=None,
                 message_id=None):
        """Constructor for the MarkMessageAsReadRequest class"""

        # Initialize members of the class
        self.messaging_product = messaging_product 
        self.status = status 
        self.message_id = message_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        messaging_product = dictionary.get("messaging_product") if dictionary.get("messaging_product") else None
        status = dictionary.get("status") if dictionary.get("status") else None
        message_id = dictionary.get("message_id") if dictionary.get("message_id") else None
        # Return an object of this model
        return cls(messaging_product,
                   status,
                   message_id)
